spring.application.name=films
spring.main.banner-mode=off
spring.elasticsearch.username=elastic
spring.elasticsearch.password=b9gM_zy=m*6PHRqs+-O-
#spring.elasticsearch.api-key=AAEAAWVsYXN0aWMva2liYW5hL2Vucm9sbC1wcm9jZXNzLXRva2VuLTE3NzAwODAyNzUyMjM6cjB5cldIQVlTZjJmX3dQTlBjem9wZw


spring.elasticsearch.uris=https://localhost:9200
#spring.elasticsearch.username=elastic
#spring.elasticsearch.password=Q-22xa8i=zKkSA87zqVe

## Ensure the TrustStore settings from the previous step are still there
#spring.elasticsearch.rest.ssl.trust-store=classpath:http_ca.crt
#spring.elasticsearch.rest.ssl.trust-store-password=


supported.extensions=.mkv,.mp4,.avi,.mov,.flv,.wmv,.mpeg,.mpg,.3gp,.webm,.pdf,.epub



# --- SSL Configuration ---
# The port for HTTPS
server.port=8443
## The format of the keystore
server.ssl.key-store-type=PKCS12
## The path to the keystore (classpath means src/main/resources)
server.ssl.key-store=classpath:keystore.p12
## The password you chose in the openssl command
server.ssl.key-store-password=abcdefgh
## The alias you chose in the openssl command
server.ssl.key-alias=tomcat
    



#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=hanysek
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=tomcat
#server.ssl.enabled=true
#server.ssl.protocol=TLS







#spring.elasticsearch.rest.uris=https://localhost:9200
#spring.elasticsearch.rest.ssl.trust-store=classpath:es-truststore.p12
#spring.elasticsearch.rest.ssl.trust-store-password=ahnsys1
#spring.elasticsearch.rest.ssl.trust-store-type=PKCS12
#spring.elasticsearch.rest.ssl.enabled=true
#
## Client certificate configuration
#spring.elasticsearch.rest.ssl.key-store=classpath:client.p12
#spring.elasticsearch.rest.ssl.key-store-password=ahnsys1
#spring.elasticsearch.rest.ssl.key-store-type=PKCS12
#
