# --- SSL Configuration ---
# The port for HTTPS
server.port=8443
# The format of the keystore
server.ssl.key-store-type=PKCS12
# The path to the keystore (classpath means src/main/resources)
server.ssl.key-store=classpath:keystore.p12
# The password you chose in the openssl command
server.ssl.key-store-password=abcdefgh
# The alias you chose in the openssl command
server.ssl.key-alias=tomcat
    
