spring.application.name=listek-admin

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/listek}
spring.datasource.username=${DB_USERNAME:listek}
spring.datasource.password=${DB_PASSWORD:listek}

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/admin
spring.flyway.table=flyway_schema_history_admin
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

server.port=${SERVER_PORT:8090}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8180/realms/myrealm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8180/realms/myrealm/protocol/openid-connect/certs}


app.loan.repayment-day-of-month=${APP_LOAN_REPAYMENT_DAY_OF_MONTH:15}