# ===================================================================
# Activate this profile by running the application with:
# -Dspring.profiles.active=prod

server.port=9090
# Production PostgreSQL Configuration



spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# Jackson JSON Configuration
# ===================================================================
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.write-dates-as-timestamps=false

#
#
#spring.jpa.database=POSTGRESQL
# For containerized environments (e.g., Docker), use the service name of the database.
# The hostname 'postgres' matches the service name in your docker-compose.yml file.

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.datasource.hikari.maxLifetime=240000
#spring.datasource.hikari.idleTimeout=240000
#spring.datasource.hikari.connectionTimeout=30000
#spring.datasource.hikari.minimumIdle=2
#spring.datasource.hikari.maximumPoolSize=120
#spring.datasource.hikari.validationTimeout=3000