# Set the default user and password.
# NOTE: This is only used on the first boot of a new database.
# Subsequent starts will use the credentials stored in the database.
default_user = myuser
default_pass = mypassword

# Point to the definitions file to be loaded on first boot.
# This allows for pre-configuring users, vhosts, queues, etc.
management.load_definitions = /etc/rabbitmq/definitions.json
stomp.listeners.tcp.default = 61613
